wallabag_api:
    resource: "@WallabagApiBundle/Resources/config/routing-v1.yml"
    prefix:   /api/v1/

wallabag_core:
    resource: "@WallabagCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

wallabag_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: WallabagCoreBundle:Security:login }

wallabag_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: WallabagCoreBundle:Security:loginCheck }

wallabag_create_user:
    pattern: /create_user/{email}/{password}
    defaults: { _controller: WallabagCoreBundle:Security:createUser }