security:
    encoders: 
        FOS\UserBundle\Model\UserInterface: sha512
#        Wallabag\Bundle\CoreBundle\Entity\User:
#            algorithm: sha512
#            encode_as_base64: false
#            iterations: 1

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        user_provider:
            id: fos_user.user_provider.username
#            id: platform.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

#        secured_area:
#            pattern: ^/demo/secured/
#            form_login:
#                provider: user_provider
#                csrf_provider: form.csrf_provider
#                provider: user_provider
#                check_path: wallabag_oauth_server_auth_login_check
#                login_path: wallabag_oauth_server_auth_login
#                username_parameter: login
#                password_parameter: password
#                use_referer:        true
#            logout:
#                path: _demo_logout
#                target: _demo
#            logout: true

        oauth_autorize:
            pattern: ^/oauth/v2/auth
#            pattern: ^/
            form_login: 
                check_path: wallabag_oauth_server_auth_login_check
                login_path: wallabag_oauth_server_auth_login
                always_use_default_target_path : true
                default_target_path: /
                use_referer : true
            logout: true
            anonymous: true

        api: 
            pattern: ^/api
            fos_oauth: true
            stateless: true

        login:
            pattern: ^/login$
            anonymous: true

        home:
            pattern: ^/
            anonymous: false
            logout: true
            form_login:
                provider: user_provider
                csrf_provider: form.csrf_provider

        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
