parameters:
  platform.entity.user.class: Wallabag\Bundle\CoreBundle\Entity\User
  platform.user.provider.class: Wallabag\Bundle\CoreBundle\Provider\UserProvider
  api.service.request.class: Wallabag\Bunde\CoreBundle\Services\ApiRequester

services:
  platform.user.manager:
    class: Doctrine\ORM\EntityManager
    factory_service: doctrine
    factory_method: getManagerForClass
    arguments:
      - "%platform.entity.user.class%"

  platform.user.repository:
    class: Wallabag\Bundle\CoreBundle\Repository\UserRepository
    factory_service: platform.user.manager
    factory_method: getRepository
    arguments:
      - "%platform.entity.user.class%"

  platform.user.provider:
    class: "%platform.user.provider.class%"
    arguments:
      - @platform.user.repository

  api.service.request:
    class: "%api.service.request.class%"
    arguments:
      - "%oauth_url"
      - "%oauth_client%"
      - "%oauth_secret%"
