parameters:
  platform.entity.user.class: Wallabag\Bundle\CoreBundle\Entity\User
  platform.user.provider.class: Wallabag\Bundle\CoreBundle\Provider\UserProvider
  api.service.request.class: Wallabag\Bundle\CoreBundle\Services\ApiRequester
  adoy_oauth2.client.class: OAuth2\Client
  api.service.client.class: Wallabag\Bundle\CoreBundle\Services\OAuth2Client

services:
  platform.user.manager:
    class: Doctrine\ORM\EntityManager
    factory_service: doctrine
    factory_method: getManagerForClass
    arguments:
      - "%platform.entity.user.class%"

  platform.user.repository:
    class: Wallabag\Bundle\CoreBundle\Repository\UserRepository
    factory_service: platform.user.manager
    factory_method: getRepository
    arguments:
      - "%platform.entity.user.class%"

  platform.user.provider:
    class: "%platform.user.provider.class%"
    arguments:
      - @platform.user.repository

#  api.service.request:
#    class: "%api.service.request.class%"
#    arguments:
#      - "%oauth_url%"
#      - "%oauth_client%"
#      - "%oauth_secret%"

  adoy_oauth2.client:
    class: "%adoy_oauth2.client.class%"
    arguments:
      - "%oauth2_client_id%"
      - "%oauth2_client_secret%"
      - "2"

  api.service.client.credentials_client:
    class: "%api.service.client.class%"
    arguments:
      - "@adoy_oauth2.client"
      - "%oauth2_auth_endpoint%"
      - "%oauth2_token_endpoint%"
      - "%oauth2_redirect_url%"
      - "client_credentials"
      - { client_id: "%oauth2_client_id%", client_secret: "%oauth2_client_secret%" }

  api.service.client.authorize_client:
    class: "%api.service.client.class%"
    arguments:
      - "@adoy_oauth2.client"
      - "%oauth2_auth_endpoint%"
      - "%oauth2_token_endpoint%"
      - "%oauth2_redirect_url%"
      - "authorization_code"
      - {redirect_uri: "%oauth2_redirect_url%"}
